
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: C:/Users/Sebastian/esp/gatt_server_service_table/fonts/bt_logo.xml
* name: bt_logo
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_bt_logo[56] = {
    // ██████∙███████
    // ██████∙∙██████
    // ██████∙∙∙█████
    // ██████∙∙∙∙████
    // ██████∙∙█∙∙███
    // ██████∙∙██∙∙██
    // ██████∙∙███∙∙█
    // ∙∙████∙∙███∙∙∙
    // ∙∙∙███∙∙███∙∙∙
    // █∙∙∙██∙∙██∙∙∙█
    // ██∙∙∙█∙∙█∙∙∙██
    // ███∙∙∙∙∙∙∙∙███
    // ████∙∙∙∙∙∙████
    // █████∙∙∙∙█████
    // █████∙∙∙∙█████
    // ████∙∙∙∙∙∙████
    // ███∙∙∙∙∙∙∙∙███
    // ██∙∙∙█∙∙█∙∙∙██
    // █∙∙∙██∙∙██∙∙∙█
    // ∙∙∙███∙∙███∙∙∙
    // ∙∙████∙∙███∙∙∙
    // ██████∙∙███∙∙█
    // ██████∙∙██∙∙██
    // ██████∙∙█∙∙███
    // ██████∙∙∙∙████
    // ██████∙∙∙█████
    // ██████∙∙██████
    // ██████∙███████
    0xfd, 0xfc, 
    0xfc, 0xfc, 
    0xfc, 0x7c, 
    0xfc, 0x3c, 
    0xfc, 0x9c, 
    0xfc, 0xcc, 
    0xfc, 0xe4, 
    0x3c, 0xe0, 
    0x1c, 0xe0, 
    0x8c, 0xc4, 
    0xc4, 0x8c, 
    0xe0, 0x1c, 
    0xf0, 0x3c, 
    0xf8, 0x7c, 
    0xf8, 0x7c, 
    0xf0, 0x3c, 
    0xe0, 0x1c, 
    0xc4, 0x8c, 
    0x8c, 0xc4, 
    0x1c, 0xe0, 
    0x3c, 0xe0, 
    0xfc, 0xe4, 
    0xfc, 0xcc, 
    0xfc, 0x9c, 
    0xfc, 0x3c, 
    0xfc, 0x7c, 
    0xfc, 0xfc, 
    0xfd, 0xfc
};
const tImage bt_logo = { image_data_bt_logo, 14, 28,
    8 };

